
version: "3.7"
services:
  client:
    container_name: client_container
    build: .
    command: "npm run start"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - database_my-network

  server:
    container_name: server_container
    build: .
    working_dir: /app/server
    command: "npm run start"
    ports:
      - "3333:3333"
    restart: always
    networks:
      - database_my-network

networks:
  database_my-network:
    external: true
